sude: require
dist: trusty
addons:
  chrome: stable
services:
    - docker

before_install:
    - google-chrome-stable --headless --disable-gpu --remote-debugging-port=9222 http://localhost &
    - docker build -t minneanimal/minneapp-angular -f Dockerfile.dev .

script: 
    - docker run minneanimal/minneapp-angular npm test