sude: require
services:
    - docker
addons:
    apt:
        sources:
        - google-chrome
        packages:
        - google-chrome-stable

before_install:
    - docker build -t minneanimal/minneapp-angular -f Dockerfile.dev .

script: 
    - docker run minneanimal/minneapp-angular npm run test -- --no-watch --no-progress --browsers=ChromeHeadlessNoSandbox
      